version: "3"
services:
 db:
  image: postgres:latest
  container_name: db
  ports:
   - '5432:5432'
  volumes:
   - postgres_data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: new_book_db
   PGDATA: /var/lib/postgresql/data
  networks:
   - motornet
  restart: always

 app:
  container_name: app
  image: motoralex73/repo:latest
  ports:
   - '8080:8080'
  networks:
   - motornet
  depends_on:
   - db
  environment:
   POSTGRES_HOST: db
#   POSTGRES_PORT: 5432
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: 123
#   POSTGRES_DB: new_book_db
  healthcheck:
   test: ["CMD", "pg_isready", "--host=db", "--port=5432", "--username=postgres"]
   retries: 3
   timeout: 5s
  links:
   - db
  restart: always

 nginx:
  image: nginx:1.26-alpine
  container_name: nginx
  volumes:
   - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
   - db
   - app
  ports:
   - '8989:8989'

networks:
 motornet:
  driver: bridge

volumes:
 postgres_data: