<!--psql -d postgres -U postgres -W -->

CREATE DATABASE new_book_db;
CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL,
    password varchar(100) NOT NULL,
    role varchar(100) NOT NULL
);
CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    taken_at date,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
);

INSERT INTO Person (full_name, year_of_birth, password, role) VALUES ('Атуров Алексей', 1973, '$2a$10$GTq5BYN/uKfrsrP8K/EClufjHgyyHqWlyqbInakJD8GpZWZrj76FO', 'ROLE_USER');
INSERT INTO Person (full_name, year_of_birth, password, role) VALUES ('Вася Рогов', 1996, '$2a$10$bfY3z48eP5aDyk4KA3cMP.8cIZuj3iv7x9RICWMwP2bDVpOn9Qde6', 'ROLE_USER');
